name: Publish Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write 

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.15"
          cache: "yarn"

      - name: Install
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

  deploy-github-pages:
    runs-on: ubuntu-latest
    needs: build-and-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.15"
          cache: "yarn"

      # Build base package, so links work
      - name: Install
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build

      # For the mobx example
      - name: Install
        run: yarn install --frozen-lockfile --non-interactive
        working-directory: ./docs/todo-mobx-example

      - name: Build
        run: yarn build
        working-directory: ./docs/todo-mobx-example

      - name: Copy output
        run: mv docs/todo-mobx-example/dist docs/public && mv docs/public/dist docs/public/todo-mobx-example
      # End mobx example

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public

  publish:
    if: github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'release-major') || contains(github.event.pull_request.labels.*.name, 'release-minor') || contains(github.event.pull_request.labels.*.name, 'release-patch'))
    needs: build-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Determine version type from label
        id: version-type
        run: |
          LABELS='${{ toJson(github.event.pull_request.labels.*.name) }}'
          if echo $LABELS | grep -a "release-major"; then
            VERSION_TYPE="major"
          elif echo $LABELS | grep -a "release-minor"; then
            VERSION_TYPE="minor"
          elif echo $LABELS | grep -a "release-patch"; then
            VERSION_TYPE="patch"
          else
            echo "::error::No valid release label found (release-major, release-minor, release-patch)."
            exit 1
          fi
          echo "type=$VERSION_TYPE" >> $GITHUB_OUTPUT
          echo "Running a $VERSION_TYPE release"

      - name: Configure git access
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.JAM_GIT_PUSHER_APP_ID }}
          private-key: ${{ secrets.JAM_GIT_PUSHER_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Configure git author
        run: |
          git config user.name GitHub Actions
          git config user.email github-actions@github.com

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.15"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build

      - name: Tag release
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION_TYPE="${{ steps.version-type.outputs.type }}"
          yarn version --"$VERSION_TYPE" --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git add package.json
          git commit -m "release: bump version to $NEW_VERSION"
          git tag v$NEW_VERSION
          git push --tags origin main

      - name: Create a GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump-version.outputs.new_version }}
          release_name: v${{ steps.bump-version.outputs.new_version }}
          draft: false
          prerelease: false

      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
